# Generated by Django 5.0.4 on 2024-04-16 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrackedPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5_hash', models.CharField(max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_cracked', models.BooleanField(default=False)),
                ('cracked_password', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cracked_passwords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
